# Generated by Django 4.2 on 2024-03-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_phisycaluser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phisycaluser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
