# Generated by Django 4.2 on 2024-03-07 14:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phisycaluser',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
