# Generated by Django 4.2 on 2024-03-11 12:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_phisycaluser_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaluser',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Контактный номер'),
        ),
    ]
